"""
Data models for Code Agent sessions.

Frozen/immutable where possible (PlannedFile, TestResult).
Mutable where lifecycle tracking requires it (GeneratedFile, WrittenFile).
"""

import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class PlannedFile:
    """A file that the Code Agent plans to create/modify."""
    path: str                          # Relative to project root
    purpose: str                       # What this file does
    complexity: str = "medium"         # low/medium/high
    dependencies: tuple = ()           # Other planned files this depends on
    is_test: bool = False              # Test file flag

    def to_dict(self) -> Dict[str, Any]:
        return {
            "path": self.path,
            "purpose": self.purpose,
            "complexity": self.complexity,
            "dependencies": list(self.dependencies),
            "is_test": self.is_test,
        }


@dataclass
class GeneratedFile:
    """Code generated by LLM for a planned file."""
    path: str
    content: str
    syntax_valid: bool = False         # ast.parse passed
    llm_source: str = ""               # "claude" or "codex"
    generation_time_ms: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "path": self.path,
            "content_length": len(self.content),
            "syntax_valid": self.syntax_valid,
            "llm_source": self.llm_source,
            "generation_time_ms": round(self.generation_time_ms, 1),
        }


@dataclass(frozen=True)
class WrittenFile:
    """A file successfully written to disk via OpenClaw."""
    path: str
    content_hash: str                  # sha256 of content
    size_bytes: int
    verified: bool = False             # Read-back matched

    def to_dict(self) -> Dict[str, Any]:
        return {
            "path": self.path,
            "content_hash": self.content_hash[:12],
            "size_bytes": self.size_bytes,
            "verified": self.verified,
        }


@dataclass(frozen=True)
class TestResult:
    """Result of running pytest via OpenClaw."""
    run_number: int
    command: str
    exit_code: int
    stdout: str
    stderr: str = ""
    passed: int = 0
    failed: int = 0
    errors: tuple = ()                 # Error messages extracted from output
    timestamp: float = field(default_factory=time.time)

    @property
    def success(self) -> bool:
        return self.exit_code == 0 and self.failed == 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "run_number": self.run_number,
            "exit_code": self.exit_code,
            "passed": self.passed,
            "failed": self.failed,
            "success": self.success,
            "errors": list(self.errors),
            "timestamp": self.timestamp,
        }


@dataclass
class ApprovalCheckpoint:
    """A point where operator approval is required."""
    name: str                          # "plan_review", "code_review", "self_modify"
    request_id: str = ""               # From ApprovalQueue
    status: str = "pending"            # pending/approved/rejected/expired
    data: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "request_id": self.request_id,
            "status": self.status,
            "timestamp": self.timestamp,
        }
