"""
PDF export for Telegram task results.

Generates PDF from Claude/Codex task results and sends via Telegram.
Uses fpdf2 + DejaVu font for Polish character support.
"""

import logging
import os
import tempfile
import time
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Font path for Polish chars
_DEJAVU_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
_DEJAVU_BOLD_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
_DEJAVU_MONO_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"


def generate_task_pdf(
    task_id: str,
    backend: str,
    task_text: str,
    result: str,
    duration_ms: Optional[float] = None,
    timestamp: Optional[float] = None,
) -> Optional[str]:
    """
    Generate PDF from task result.

    Args:
        task_id: Task identifier
        backend: "claude" or "codex"
        task_text: Original task description
        result: Full result text (not truncated)
        duration_ms: Execution time in ms
        timestamp: When task was created

    Returns:
        Path to generated PDF file, or None on error.
    """
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        # Load fonts with Polish support
        has_dejavu = os.path.exists(_DEJAVU_PATH)
        if has_dejavu:
            pdf.add_font("DejaVu", "", _DEJAVU_PATH)
            if os.path.exists(_DEJAVU_BOLD_PATH):
                pdf.add_font("DejaVu", "B", _DEJAVU_BOLD_PATH)
            if os.path.exists(_DEJAVU_MONO_PATH):
                pdf.add_font("DejaVuMono", "", _DEJAVU_MONO_PATH)
            font = "DejaVu"
            mono = "DejaVuMono" if os.path.exists(_DEJAVU_MONO_PATH) else "DejaVu"
        else:
            font = "Helvetica"
            mono = "Courier"

        # Header
        pdf.set_font(font, "B", 16)
        label = {"claude": "Claude Code", "codex": "Codex (ChatGPT)"}.get(
            backend, backend)
        pdf.cell(text=f"M.A.R.I.A. - {label}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # Metadata
        pdf.set_font(font, "", 9)
        pdf.set_text_color(100, 100, 100)
        ts = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(timestamp or time.time()))
        dur_str = f" | {duration_ms/1000:.1f}s" if duration_ms else ""
        pdf.cell(text=f"Task: {task_id} | {ts}{dur_str}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(6)

        # Task description
        pdf.set_text_color(0, 0, 0)
        pdf.set_font(font, "B", 11)
        pdf.cell(text="Zadanie:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font(font, "", 10)
        pdf.multi_cell(w=0, text=task_text)
        pdf.ln(6)

        # Separator
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        # Result
        pdf.set_font(font, "B", 11)
        pdf.cell(text="Wynik:", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # Render result - handle code blocks simply
        pdf.set_font(font, "", 10)
        _render_result(pdf, result, font, mono)

        # Footer
        pdf.ln(10)
        pdf.set_font(font, "", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(text=f"Generated by M.A.R.I.A. | {backend} | {task_id}")

        # Save to temp file
        out_dir = Path(tempfile.gettempdir()) / "maria_pdf"
        out_dir.mkdir(exist_ok=True)
        filename = f"maria_{backend}_{task_id}.pdf"
        out_path = str(out_dir / filename)
        pdf.output(out_path)

        logger.info("[PDF] Generated: %s (%d bytes)", out_path, os.path.getsize(out_path))
        return out_path

    except Exception as e:
        logger.warning("[PDF] Generation failed: %s", e)
        return None


def _render_result(pdf, text: str, font: str, mono: str) -> None:
    """
    Render result text with basic code block detection.

    Lines between ``` markers are rendered in monospace.
    """
    in_code = False
    lines = text.split("\n")
    lm = pdf.l_margin  # save left margin for cursor reset

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code = not in_code
            if in_code:
                pdf.ln(2)
                pdf.set_fill_color(245, 245, 245)
            else:
                pdf.ln(2)
            continue

        # Reset cursor to left margin before each line
        pdf.set_x(lm)

        if in_code:
            pdf.set_font(mono, "", 9)
            pdf.multi_cell(w=0, text=f"  {line}", new_x="LMARGIN", new_y="NEXT")
        else:
            if stripped.startswith("#") or stripped.startswith("**"):
                clean = stripped.lstrip("#").strip().strip("*").strip()
                if clean:
                    pdf.set_font(font, "B", 10)
                    pdf.multi_cell(w=0, text=clean, new_x="LMARGIN", new_y="NEXT")
                    pdf.set_font(font, "", 10)
            elif stripped.startswith("- ") or stripped.startswith("* "):
                pdf.multi_cell(w=0, text=f"  {stripped}", new_x="LMARGIN", new_y="NEXT")
            elif not stripped:
                pdf.ln(3)
            else:
                pdf.multi_cell(w=0, text=line, new_x="LMARGIN", new_y="NEXT")
